### ISSUE TITLE
Topblock hologram not updated

### ISSUE THREAD

**Issue by Moltanicaa** [BentoBoxWorld/TopBlock#3]
### Expected behavior

For some reason, the information in the playholders is only updated when the server is restarted.

### Observed/Actual behavior

Incorrect value (33268) when uses /papi parse me %aoneblock_island_count_top_2%

### Steps/models to reproduce

I use CMI Hologram. What else needs to be provided?

```
top_block:
  Loc: oneblock_world;800.36;83.75;7.35
  Interval: 240.0
  HoverParticles:
    Count: 1
  Range: 16
  RangeExtra: 16
  Lines:
  - '&b&lТоп по вскопанным блокам'
  - '&b'
  - '&3#1 &7| &b%aoneblock_island_member_names_top_1% %aoneblock_island_phase_name_top_1%&7:
    &f%aoneblock_island_lifetime_top_1% &fблоков'
  - '&3#2 &7| &b%aoneblock_island_member_names_top_2% %aoneblock_island_phase_name_top_2%&7:
    &f%aoneblock_island_lifetime_top_2% &fблоков'
  - '&3#3 &7| &b%aoneblock_island_member_names_top_3% %aoneblock_island_phase_name_top_3%&7:
    &f%aoneblock_island_lifetime_top_3% &fблоков'
  - '&3#4 &7| &b%aoneblock_island_member_names_top_4% %aoneblock_island_phase_name_top_4%&7:
    &f%aoneblock_island_lifetime_top_4% &fблоков'
  - '&3#5 &7| &b%aoneblock_island_member_names_top_5% %aoneblock_island_phase_name_top_5%&7:
    &f%aoneblock_island_lifetime_top_5% &fблоков'
  - '&3#6 &7| &b%aoneblock_island_member_names_top_6% %aoneblock_island_phase_name_top_6%&7:
    &f%aoneblock_island_lifetime_top_6% &fблоков'
  - '&3#7 &7| &b%aoneblock_island_member_names_top_7% %aoneblock_island_phase_name_top_7%&7:
    &f%aoneblock_island_lifetime_top_7% &fблоков'
  - '&3#8 &7| &b%aoneblock_island_member_names_top_8% %aoneblock_island_phase_name_top_8%&7:
    &f%aoneblock_island_lifetime_top_8% &fблоков'
  - '&3#9 &7| &b%aoneblock_island_member_names_top_9% %aoneblock_island_phase_name_top_9%&7:
    &f%aoneblock_island_lifetime_top_9% &fблоков'
  - '&3#10 &7| &b%aoneblock_island_member_names_top_10% %aoneblock_island_phase_name_top_10%&7:
    &f%aoneblock_island_lifetime_top_10% &fблоков'
  - '&7'
  - '&3Ваши вскопанные блоки&7: &f%aoneblock_my_island_lifetime_count% блоков'
```

 I see 33268, but correct is 33300
![Без имени](https://github.com/BentoBoxWorld/TopBlock/assets/59089206/20b675c7-a8dc-41a2-b1df-2594fc5e5954)

### BentoBox version

Last

### Plugin list

i dont know how to copy from chat
![image](https://github.com/BentoBoxWorld/TopBlock/assets/59089206/75b16e63-4d8f-405f-ab3f-7ce81c938cae)

**Comment by tastybento** [comment]
Everything is updated every 5 minutes. You can speed up the checking if you like in the TopBlock [config.yml file](https://github.com/BentoBoxWorld/TopBlock/blob/02805541489c6d42dd94ce5b42d50457af0c073f/src/main/resources/config.yml#L5):

```
# How often the Top Ten should be refreshed in minutes. Minimum is 1 minute, default is 5.
# Each refresh requires reading every island from the database, so this should not be done too often.
refresh-time: 5
```

The update is not instantaneous because blocks can be broken very quickly by many players so the count is checked periodically.

**Comment by Moltanicaa** [comment]
It is not updated, we checked.

**Comment by tastybento** [comment]
Found the bug. Fixing.

**Comment by tastybento** [comment]
I found the issue - the count is not saved by AOneBlock unless the player logs out right now.

**Comment by tastybento** [comment]
Okay, fixed. The placeholders were not updating dynamically as you found. There are some quirks though:

1. When players are playing, their status is only saved every 50 blocks to the database so while they are playing, any top ten values will be in 50 block increments
2. When the player logs off, their state is saved, so their actual count will show up.
3. The top ten itself is only updated every 5 minutes by default.

I'll do a release of this fix.
