### ISSUE TITLE
my stats

### ISSUE THREAD

**Issue by Mithranduil** [BentoBoxWorld/TopBlock#6]
### Is your feature request related to a problem?

no, its only an feature that currently didnt exist

### Describe the solution you'd like.

it would be nice to add an placeholder like "%aoneblock_island_lifetime_yourstats%" or something like this to print my current stats in an likely hologram or chat.

### Describe alternatives you've considered.

tried with the current placeholders, but didnt work.
Don't want to use the command.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
This is doable. Can you give an example of what the stats would be?

**Comment by Mithranduil** [comment]
the amount of blocks myself has break in oneblock.

currently it gives only the placeholders to show the ranks an positions (with numbers), but not my count.

**Comment by tastybento** [comment]
Oh, you can get those directly from AOneBlock already:

https://docs.bentobox.world/en/latest/gamemodes/AOneBlock/#placeholders
